[list]
    [list.default]
        name = "default"
        user ="root"
        password = "Abc123456"
        ip = "172.25.114.1"
        port = 3306
        db = "gateway"
        parameter = "charset=utf8mb4&parseTime=True&loc=Local"